apiVersion: apps/v1
kind: Deployment
metadata:
  name: projecteren-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: projecteren
  template:
    metadata:
      labels:
        app: projecteren
    spec:
      containers:
        - name: projecteren
          image: projecteren:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
