apiVersion: apps/v1
kind: Deployment
metadata:
  name: projecteren-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: projecteren
  template:
    metadata:
      labels:
        app: projecteren
    spec:
      containers:
        - name: projecteren
          image: projecteren:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: spring-db-secret
                  key: db-url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: spring-db-secret
                  key: db-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: spring-db-secret
                  key: db-password
            - name: APP_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwtSecretKey
            - name: APP_JWT_EXPIRATION_MS
              value: "3600000"
          volumeMounts:
            - name: config-volume
              mountPath: /config
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: spring-app-config
