name: Spring Boot Multi-Job CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Kodları Checkout Et
        uses: actions/checkout@v3

      - name: Java Kurulumu
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Maven Wrapper’a İzin Ver
        run: chmod +x mvnw

      - name: Projeyi Build Et
        run: ./mvnw clean install

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Kodları Checkout Et
        uses: actions/checkout@v3

      - name: Java Kurulumu
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Testleri Çalıştır
        run: ./mvnw test
